### PR TITLE
Add automplete for categories

### PR DESCRIPTION
**Pull request by Sacret**
It would be nice to have autocomplete option for category on `Add recipe` page. I have implemented this functionality using `Typeahead`: http://angular-ui.github.io/bootstrap/versioned-docs/0.13.0/#/typeahead

### CODE REVIEW

**Comment by Sacret** [comment]
This PR and https://github.com/kylec32/recipe-holder/pull/12 have some crossing changes. So if you merge this one first please notify @jsjaskaran to update his code. Or if you merge PR 12 first notify me.
Thanks!

**Comment by kylec32** [comment]
Thank you for the heads up.

**Comment by kylec32** [comment]
So am I seeing this correctly that it doesn't matter what the content in the input is, it just shows all of the possible categories? (Other than the highlighting I guess.)

**Comment by Sacret** [comment]
Yeah, you're right. I will improve my code to show only categories which contain text from input

**Comment by Sacret** [comment]
I have added a filter to display categories which contain symbols from text input.
@kylec32 please take a look!

**Comment by kylec32** [comment]
Awesome! Thank you for your help.

**Pull request merged**
